import js from "@eslint/js";

export default [
  // Generated by build-web.sh and Playwright: the same paths .prettierignore skips.
  { ignores: ["pkg/", "playwright-report/", "test-results/"] },
  js.configs.recommended,
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        document: "readonly",
        window: "readonly",
        console: "readonly",
      },
    },
  },
  {
    files: ["e2e/**/*.js", "playwright.config.js", "eslint.config.js"],
    languageOptions: {
      globals: {
        process: "readonly",
      },
    },
  },
];
